spring:
  application:
    name: NotificationService
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      group-id: notification-service
      properties:
        spring:
          json:
            trusted:
              package: "*"
    topic:
      name: userEventTopic

server:
  port: 4002
